RAW_DATA_PATH = 'data//raw_data_20190511.p'
PROCESSED_DATA_PATH = 'data//processed_data.p'
BOW_MODEL_PATH = 'data//bow_model.p'
WORD2VEC_MODEL_PATH = 'data//word2vec_model.p'
FASTTEXT_MODEL_PATH = 'data//fasttext_model'